# Site settings
title: Zac Willmington Web Developer
header-img: img/home-bg.png
email: zac.willmington@gmail.com
copyright_name: zacwillmington
description: > # this means to ignore newlines until "baseurl:"
  Fullstack Dev
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zacwillmington
learn_profile: zacwillmington
email_username: zac.willmington@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
